# Generated by Django 5.0.1 on 2024-01-20 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verification',
            old_name='updated_at',
            new_name='timestamp',
        ),
        migrations.AddField(
            model_name='user',
            name='user_exist',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
