# Generated by Django 5.0.1 on 2024-01-20 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_updated_at_verification_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
