# Generated by Django 5.0.1 on 2024-01-20 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_amount_user_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_exist',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
