# Generated by Django 5.0.1 on 2024-01-20 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictandwin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coin',
            name='head',
        ),
        migrations.RemoveField(
            model_name='coin',
            name='tail',
        ),
        migrations.AddField(
            model_name='coin',
            name='side',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='stake',
            name='prediction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='predictandwin.coin'),
        ),
    ]
